#!/usr/bin/env bash
# Batch-generate a few brand/system visuals via FAL Qwen Image Edit.
# This uses an input image and applies different prompts to produce variants.
# Outputs into webapp-v3/public/generated by default.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
OUT_DIR="$REPO_ROOT/webapp-v3/public/generated"

mkdir -p "$OUT_DIR"

if [[ -z "${FAL_KEY:-}" ]]; then
  echo "FAL_KEY is not set. export FAL_KEY=..." >&2
  exit 1
fi

# Built-in neutral white 1x1 PNG data URI (avoids any beach/landscape bias)
# Will be upscaled by the API to the configured size (square_hd by default).
NEUTRAL_DATA_URI="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAuMBg7d1bdsAAAAASUVORK5CYII="

# Flags
FORCE=0

# Simple arg parsing: optional --force flag and optional input file.
# If no input provided or the special value 'neutral' is used, we'll use the built-in neutral seed.
if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
  FORCE=1
  shift || true
fi

INPUT_FILE="${1:-neutral}"

if [[ "$INPUT_FILE" != "neutral" && ! -f "$INPUT_FILE" ]]; then
  echo "Input file not found: $INPUT_FILE" >&2
  echo "Tip: run with 'neutral' to use a built-in blank seed (no beach)." >&2
  exit 1
fi

PROMPTS=(
  # 0: Create a minimalist app icon with a camera lens and subtle gradient
  "Create a minimalist app icon with a camera lens and subtle gradient"
  # 1: Generate a square logo badge inspired by photo albums, flat style
  "Generate a square logo badge inspired by photo albums, flat style"
  # 2: Create a playful spark/starburst overlay icon for smart search feature
  "Create a playful spark/starburst overlay icon for smart search feature"
  # 3: Design a modern library icon: bookshelf with photo frames
  "Design a modern library icon: bookshelf with photo frames"
  # 4: Generate a search icon: magnifying glass with photo overlay
  "Generate a search icon: magnifying glass with photo overlay"
  # 5: Create a collections icon: stacked photo cards in a folder
  "Create a collections icon: stacked photo cards in a folder"
  # 6: Design a people icon: silhouette group with faces
  "Design a people icon: silhouette group with faces"
  # 7: Generate a places icon: map pin with camera
  "Generate a places icon: map pin with camera"
  # 8: Create a tags icon: label tags with photo attachments
  "Create a tags icon: label tags with photo attachments"
  # 9: Design a trips icon: calendar with photo markers
  "Design a trips icon: calendar with photo markers"
  # 10: Generate a favorites icon: heart with photo inside
  "Generate a favorites icon: heart with photo inside"
  # 11: Create an analytics icon: bar chart with photo data points
  "Create an analytics icon: bar chart with photo data points"
  # 12: Design a settings icon: gear with camera lens
  "Design a settings icon: gear with camera lens"
  # 13: Generate a close icon: X mark with subtle photo background
  "Generate a close icon: X mark with subtle photo background"
  # 14: Create a theme toggle icon: sun/moon transition
  "Create a theme toggle icon: sun/moon transition"
  # 15: Design a back arrow icon: arrow with photo trail
  "Design a back arrow icon: arrow with photo trail"
  # 16: Generate a forward arrow icon: arrow with photo trail
  "Generate a forward arrow icon: arrow with photo trail"
  # 17: Create a grid view icon: photo grid layout
  "Create a grid view icon: photo grid layout"
  # 18: Design a list view icon: photo list with thumbnails
  "Design a list view icon: photo list with thumbnails"
  # 19: Generate a map view icon: map with photo pins
  "Generate a map view icon: map with photo pins"
  # 20: Design a subtle background pattern with geometric shapes and soft colors for app UI
  "Design a subtle background pattern with geometric shapes and soft colors for app UI"
  # 21: Generate an illustration of a camera with film strips and vintage elements
  "Generate an illustration of a camera with film strips and vintage elements"
  # 22: Create a modern icon set: search magnifying glass with photo overlay
  "Create a modern icon set: search magnifying glass with photo overlay"
  # 23: Design a background texture with abstract photo frames and light gradients
  "Design a background texture with abstract photo frames and light gradients"
  # 24: Generate an illustration of a photo gallery with floating images and soft shadows
  "Generate an illustration of a photo gallery with floating images and soft shadows"
  # 25: Create a minimalist icon for collections: stacked photo cards
  "Create a minimalist icon for collections: stacked photo cards"
  # 26: Design a subtle pattern background with camera silhouettes and bokeh effects
  "Design a subtle pattern background with camera silhouettes and bokeh effects"
  # 27: Generate a seamless texture with film grain and photo borders
  "Generate a seamless texture with film grain and photo borders"
  # 28: Create a background pattern with overlapping photo corners
  "Create a background pattern with overlapping photo corners"
  # 29: Design a subtle gradient background with camera aperture motifs
  "Design a subtle gradient background with camera aperture motifs"
  # 30: Generate a texture with soft photo shadows and highlights
  "Generate a texture with soft photo shadows and highlights"
  # 31: Create a pattern background with miniature camera icons
  "Create a pattern background with miniature camera icons"
  # 32: Illustrate an empty photo library with camera and film strips
  "Illustrate an empty photo library with camera and film strips"
  # 33: Generate an onboarding illustration: person uploading photos
  "Generate an onboarding illustration: person uploading photos"
  # 34: Create an illustration for search results: magnifying glass finding photos
  "Create an illustration for search results: magnifying glass finding photos"
  # 35: Design an empty collections state: folder with photo placeholders
  "Design an empty collections state: folder with photo placeholders"
  # 36: Generate an illustration for people clustering: faces connecting
  "Generate an illustration for people clustering: faces connecting"
  # 37: Create an empty places view: map with photo pins waiting
  "Create an empty places view: map with photo pins waiting"
  # 38: Design an illustration for tag management: labels organizing photos
  "Design an illustration for tag management: labels organizing photos"
  # 39: Generate a trip planning illustration: calendar with photo itinerary
  "Generate a trip planning illustration: calendar with photo itinerary"
  # 40: Create an empty favorites state: heart with photo outlines
  "Create an empty favorites state: heart with photo outlines"
  # 41: Design an analytics dashboard illustration: charts with photo metrics
  "Design an analytics dashboard illustration: charts with photo metrics"
  # 42: Generate a welcome screen illustration: camera welcoming user
  "Generate a welcome screen illustration: camera welcoming user"
  # 43: Create an error state illustration: camera with warning sign
  "Create an error state illustration: camera with warning sign"
  # 44: Design a loading illustration: camera processing film
  "Design a loading illustration: camera processing film"
  # 45: Generate a success illustration: camera with checkmark
  "Generate a success illustration: camera with checkmark"
  # 46: Create a no results illustration: search glass with empty frame
  "Create a no results illustration: search glass with empty frame"
  # 47: Create a subtle canvas background with floating geometric shapes and soft gradients
  "Create a subtle canvas background with floating geometric shapes and soft gradients"
  # 48: Generate an abstract background pattern with interconnected photo frames
  "Generate an abstract background pattern with interconnected photo frames"
  # 49: Design a minimalist canvas texture with camera lens motifs and light diffusion
  "Design a minimalist canvas texture with camera lens motifs and light diffusion"
  # 50: Create a soft background with overlapping translucent photo silhouettes
  "Create a soft background with overlapping translucent photo silhouettes"
  # 51: Generate a canvas pattern with subtle film strip elements and vintage borders
  "Generate a canvas pattern with subtle film strip elements and vintage borders"
  # 52: Design an ethereal background with floating camera apertures and bokeh effects
  "Design an ethereal background with floating camera apertures and bokeh effects"
  # 53: Create a canvas texture with abstract photo composition lines and soft shadows
  "Create a canvas texture with abstract photo composition lines and soft shadows"
  # 54: Generate a subtle background pattern with miniature photography icons
  "Generate a subtle background pattern with miniature photography icons"
  # 55: Design a canvas background with flowing photo ribbon elements
  "Design a canvas background with flowing photo ribbon elements"
)

for i in "${!PROMPTS[@]}"; do
  asset_file="$OUT_DIR/asset_${i}.png"
  data_uri_file="$OUT_DIR/asset_${i}.datauri.txt"

  # If we already have a data URI but no PNG, backfill the PNG by decoding (no API call)
  if [[ $FORCE -ne 1 && -f "$data_uri_file" && ! -f "$asset_file" ]]; then
    echo "[${i}] Backfilling PNG from existing data URI" >&2
    data_uri=$(cat "$data_uri_file")
    payload=${data_uri#*,}
    # Try GNU then BSD base64 decode
    if ! echo "$payload" | base64 -d > "$asset_file" 2>/dev/null; then
      echo "$payload" | base64 -D > "$asset_file"
    fi
  fi

  # Skip if asset already exists unless forcing
  if [[ $FORCE -ne 1 && ( -f "$asset_file" || -f "$data_uri_file" ) ]]; then
    echo "[${i}] Skipping - asset already exists: $asset_file" >&2
    continue
  fi

  # Clean prior outputs when forcing
  if [[ $FORCE -eq 1 ]]; then
    rm -f "$asset_file" "$data_uri_file" || true
  fi

  p="${PROMPTS[$i]}"
  echo "[${i}] Prompt: $p" >&2

  # Avoid beach-like content explicitly via negative prompt
  NEG="beach, sand, ocean, shoreline, water, waves, palm trees, seascape, beach umbrella, tropical"

  # Choose image arg: neutral data URI vs file
  if [[ "$INPUT_FILE" == "neutral" ]]; then
    result=$("$SCRIPT_DIR/fal_qwen_image_edit.sh" -i "$NEUTRAL_DATA_URI" -p "$p" --negative "$NEG" -o png --sync || true)
  else
    result=$("$SCRIPT_DIR/fal_qwen_image_edit.sh" --file "$INPUT_FILE" -p "$p" --negative "$NEG" -o png --sync || true)
  fi
  # If sync mode returns data URI, store it
  data_uri=$(echo "$result" | grep -o 'data:[^" ]*' || true)
  if [[ -n "$data_uri" ]]; then
    echo "$data_uri" > "$OUT_DIR/asset_${i}.datauri.txt"
    # Also decode to PNG for easier use in CSS/HTML
    payload=${data_uri#*,}
    if ! echo "$payload" | base64 -d > "$OUT_DIR/asset_${i}.png" 2>/dev/null; then
      echo "$payload" | base64 -D > "$OUT_DIR/asset_${i}.png"
    fi
  else
    # Otherwise parse URL from JSON
    url=$(echo "$result" | grep -o '"url" *: *"[^"]*"' | sed 's/.*: *"\(.*\)"/\1/' | head -n1)
    if [[ -n "$url" ]]; then
      echo "Downloading $url" >&2
      curl -sSL "$url" -o "$OUT_DIR/asset_${i}.png" || true
    fi
  fi
 done

echo "Assets generated in: $OUT_DIR"
