// Simple store hooks to replace Zustand and eliminate infinite loops
export {
  SimpleStoreProvider,
  useAllTags,
  // UI selectors
  useBusy,
  useCamera,
  useCaptionsEnabled,
  useClusters,
  useCollections,
  useDiag,
  useEngineHealth,
  useEngineHealthHistory,
  useEngineLogs,
  // Settings selectors
  useDir,
  useEngine,
  useFastIndexEnabled,
  useFastKind,
  useFavOnly,
  useFavorites,
  useFMax,
  useFMin,
  useGroups,
  useHasText,
  useHfToken,
  useIsoMax,
  useIsoMin,
  useLibHasMore,
  useLibrary,
  useNeedsHf,
  useNeedsOAI,
  useNote,
  useOcrEnabled,
  useOpenaiKey,
  useOsTrashEnabled,
  usePersons,
  usePhotoActions,
  usePlace,
  usePoints,
  useResultViewSetting,
  useSavedSearches,
  useSearchId,
  useSearchQuery,
  // Photo selectors
  useSearchResults,
  // Actions
  useSettingsActions,
  useShowHelp,
  useShowInfoOverlay,
  useShowWelcome,
  useSimpleStore,
  useSmartCollections,
  useTagFilter,
  useTagsMap,
  useTimelineBucketSetting,
  useTopK,
  useUIActions,
  useViewMode,
  // Workspace selectors
  useWorkspace,
  useWorkspaceActions,
  useWsToggle,
  useEngineTelemetryActions,
} from "./SimpleStore";
