// Simple store hooks to replace Zustand and eliminate infinite loops
export {
  SimpleStoreProvider,
  useSimpleStore,
  // Settings selectors
  useDir,
  useEngine,
  useHfToken,
  useOpenaiKey,
  useNeedsHf,
  useNeedsOAI,
  useCamera,
  useIsoMin,
  useIsoMax,
  useFMin,
  useFMax,
  usePlace,
  useShowInfoOverlay,
  useResultViewSetting,
  useTimelineBucketSetting,
  useCaptionsEnabled,
  useOcrEnabled,
  useHasText,
  useFastIndexEnabled,
  useFastKind,
  useOsTrashEnabled,
  // Photo selectors
  useSearchResults,
  useSearchId,
  useSearchQuery,
  useTopK,
  useFavorites,
  useFavOnly,
  useTagFilter,
  useAllTags,
  useTagsMap,
  useSavedSearches,
  useCollections,
  useSmartCollections,
  useLibrary,
  useLibHasMore,
  // UI selectors
  useBusy,
  useNote,
  useViewMode,
  useShowWelcome,
  useShowHelp,
  // Workspace selectors
  useWorkspace,
  useWsToggle,
  usePersons,
  useClusters,
  useGroups,
  usePoints,
  useDiag,
  // Actions
  useSettingsActions,
  usePhotoActions,
  useUIActions,
  useWorkspaceActions,
} from './SimpleStore'
